baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hugo Snap Test'
enableGitInfo = true

[frontmatter]
lastmod = [':git']

[[module.imports]]
path = 'github.com/jmooring/hugo-content'

[[module.imports.mounts]]
source = 'content'
target = 'content'

[params]
transpiler = 'dartsass'  # dartsass or libsass

[security.exec]
allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^asciidoctor$', '^pandoc$', '^rst2html$']
